packages:
  - site
  - packages/*

allowBuilds:
  esbuild: true
  workerd: true

minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20260930.2'
  - '@cloudflare/workerd-darwin-arm64@1.20260930.2'
  - '@cloudflare/workerd-linux-64@1.20260930.2'
  - '@cloudflare/workerd-linux-arm64@1.20260930.2'
  - '@cloudflare/workerd-windows-64@1.20260930.2'
  - miniflare@5.20260930.0-alpha
  - workerd@1.20260930.2
  - wrangler@4.145.0
